  name: PR Code Quality Check

  on:
    pull_request:
      paths:
        - '**/*.cs'

  jobs:
    analyze:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup .NET SDK
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: '8.0.x'

        - name: Restore dependencies
          run: dotnet restore

        - name: Build
          run: dotnet build --no-restore

        - name: Analyze modified files
          run: |
            # Fetch the list of added or modified .cs files in the PR
            CHANGED_FILES=$(git diff --name-only --diff-filter=AM ${{ github.event.pull_request.base.sha }} ${{ github.sha }} -- '*.cs')
            if [[ -z "$CHANGED_FILES" ]]; then
              echo "No C# files were modified or added in this PR."
              exit 0
            fi

            # Run the analyzers on each changed file
            for file in $CHANGED_FILES; do
              echo "Analyzing $file"
              dotnet build --no-restore --no-incremental /p:AnalysisMode=Current /p:AnalysisLevel=latest /warnaserror
              if [ $? -ne 0 ]; then
                echo "Code analysis failed for $file. Please address the issues before merging."
                exit 1
              fi
            done
          shell: bash
